### ISSUE TITLE
Enable auto-publish

### ISSUE THREAD

**Issue by achingbrain** [alanshaw/stream-to-it#24]
This repo needs an `NPM_TOKEN` repo secret with perms to publish to [stream-to-it](https://www.npmjs.com/package/stream-to-it) for auto-publishing to work similar to https://github.com/alanshaw/it-ws/pull/6#issuecomment-1010258754

It'll also need the `gh-pages` branch publishing for the generated docs too.

Once the token is available re-triggering https://github.com/alanshaw/stream-to-it/actions/runs/8233135322/job/22512123115 should cause a new major to be published.

**Comment by achingbrain** [comment]
@alanshaw could you set the token up when you have a minute please, ta!

**Comment by alanshaw** [comment]
It done! https://github.com/alanshaw/stream-to-it/actions/runs/8233135322/job/23560074789
