### ISSUE TITLE
Handle case where body is undefined in React Native env

### ISSUE THREAD

**Issue by pcowgill** [alanshaw/stream-to-it#3]
Now that `js-ipfs-http-client` uses the `source` file in this lib, some elements from this PR https://github.com/ipfs/js-ipfs-http-client/pull/1224 will need to land here instead

**Comment by pcowgill** [comment]
@alanshaw For `js-ipfs-http-client` to work well with this repo in React Native, I was thinking of opening a PR here that would handle the case where res.body is undefined, it involves passing a whole fetch response into this helper rather than just the `readable`. Should we make a variant of the function that accepts the whole response so as not to break `js-ipfs-utils` and `js-ipfs`? Make a new repo called `response-to-it`? Other? Thanks!

I'm `pcowgill` on Telegram if you would like to chat semi-synchronously about this. Thanks!

cc @hugomrdias

**Comment by pcowgill** [comment]
@alanshaw This is how it was going to look in `js-ipfs-http-client` before I realized that helper lib was being extracted out into a shared package https://github.com/pcowgill/js-ipfs-http-client/blob/74c286ed08862fc7775a2f5ba51a44248faebcef/src/lib/stream-to-async-iterable.js

**Comment by pcowgill** [comment]
@alanshaw I'm going with this strategy for now so as to have minimal impact on `js-ipfs` and `js-ipfs-utils` https://github.com/pcowgill/js-ipfs-http-client/blob/250848946b59bd804894134ed0b0829211c28de6/src/lib/stream-to-async-iterable.js

**Comment by hugomrdias** [comment]
this package doesn't care about web `Response` or `Response.body` only streams.
IMO this issue should be handled elsewhere.

**Comment by alanshaw** [comment]
> @alanshaw I'm going with this strategy for now so as to have minimal impact on `js-ipfs` and `js-ipfs-utils` https://github.com/pcowgill/js-ipfs-http-client/blob/250848946b59bd804894134ed0b0829211c28de6/src/lib/stream-to-async-iterable.js

Agree this is the better way to go, the fix does not belong here.
